--ozone-platform-hint=auto
--ignore-gpu-blocklist
--enable-zero-copy
--enable-gpu-rasterization
--enable-oop-rasterization
--enable-gpu-compositing
--enable-accelerated-2d-canvas
--enable-accelerated-video-decode
--enable-accelerated-video-encode
--enable-accelerated-mjpeg-decode
--enable-features=WaylandWindowDecorations,VaapiVideoDecoder,VaapiVideoEncoder,VaapiIgnoreDriverChecks,CanvasOopRasterization
--disable-features=UseChromeOSDirectVideoDecoder
--enable-smooth-scrolling
--enable-media-router
--enable-webgl-developer-extensions
--disable-search-engine-collection
--extension-mime-request-handling=always-prompt-for-install
--fingerprinting-canvas-image-data-noise
--fingerprinting-canvas-measuretext-noise
--fingerprinting-client-rects-noise
--popups-to-tabs
--force-punycode-hostnames
--show-avatar-button=incognito-and-guest
--no-default-browser-check
--no-pings
--lang=es,en
--use-gl=angle
--use-angle=gl
--disable-gpu-driver-bug-workarounds
