--ignore-gpu-blocklist
--enable-zero-copy
--ozone-platform-hint=auto
--ozone-platform=wayland
--enable-wayland-ime
--process-per-site
--enable-accelerated-video-decode
--enable-accelerated-video-encode
--enable-features=WebUIDarkMode,UseOzonePlatform,VaapiVideoDecodeLinuxGL,VaapiVideoDecoder,VaapiIgnoreDriverChecks,WebRTCPipeWireCapturer,WaylandWindowDecorations,CanvasOopRasterization
--enable-gpu-rasterization
--enable-oop-rasterization
--enable-gpu-compositing
--enable-accelerated-2d-canvas
--enable-smooth-scrolling
